// Shared server-side project facts: paths inside the mounted project root,
// .env access, and docker-based stack state.

import { existsSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { parseEnvValues } from '$lib/env-file';

export const ENV_DIR = process.env.ENV_DIR ?? resolve(process.cwd(), '..');
export const ENV_FILE = join(ENV_DIR, '.env');
export const EXAMPLE_FILE = join(ENV_DIR, '.env.example');
export const RESULT_FILE = join(ENV_DIR, '.install-result');

// Images produced by build.sh; all must exist for a start to succeed.
// 'hermes' is intentionally disabled (commented out in build.sh/start.sh/compose.yml).
export const BUILT_IMAGES = ['opencode', 'bun-runner', 'nifi', 'openclaw'].map(
  (n) => `all-in-wonder/${n}:latest`
);

export function readEnvFile() {
  const exampleText = readFileSync(EXAMPLE_FILE, 'utf8');
  const envText = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, 'utf8') : '';
  return { exampleText, envText };
}

export function envValues(): Map<string, { value: string }> {
  return existsSync(ENV_FILE) ? parseEnvValues(readFileSync(ENV_FILE, 'utf8')) : new Map();
}

// "Configured" = the configuration form has been saved at least once. The save fills
// every empty autogenerated secret, so an empty DATABASE_PASSWORD means the
// .env is still the untouched copy of .env.example.
export function isConfigured(): boolean {
  return Boolean(envValues().get('DATABASE_PASSWORD')?.value);
}

export function dockerExitCode(args: string[], timeoutMs = 30_000): Promise<number> {
  return new Promise((res) => {
    const c = spawn('docker', args, { cwd: ENV_DIR, stdio: 'ignore' });
    const t = setTimeout(() => c.kill(), timeoutMs);
    c.on('error', () => {
      clearTimeout(t);
      res(1);
    });
    c.on('close', (code) => {
      clearTimeout(t);
      res(code ?? 1);
    });
  });
}

function dockerOutput(args: string[], timeoutMs = 30_000): Promise<string> {
  return new Promise((res) => {
    const c = spawn('docker', args, { cwd: ENV_DIR });
    let out = '';
    const t = setTimeout(() => c.kill(), timeoutMs);
    c.stdout.on('data', (d) => (out += d.toString()));
    c.on('error', () => {
      clearTimeout(t);
      res('');
    });
    c.on('close', () => {
      clearTimeout(t);
      res(out);
    });
  });
}

// Installation id appended to every container name (compose.yml uses
// ${APP_ID:-0}, so mirror that default).
export function appId(): string {
  return envValues().get('APP_ID')?.value || '0';
}

// The nginx proxy publishes every service URL and depends on all of them, so
// "proxy is running" is the best single signal for "the stack is up".
export async function stackState(): Promise<{ running: boolean; needBuild: boolean }> {
  const [proxy, images] = await Promise.all([
    dockerOutput(['ps', '-q', '--filter', `name=^proxy-${appId()}$`, '--filter', 'status=running']),
    dockerExitCode(['image', 'inspect', ...BUILT_IMAGES])
  ]);
  return { running: proxy.trim() !== '', needBuild: images !== 0 };
}
