// Shared server-side project facts: project-root paths, .env access, and
// docker-based stack state.

import { existsSync, readFileSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { parseEnvValues } from '$lib/env-file';

export const ENV_DIR = process.env.ENV_DIR ?? resolve(process.cwd(), '..');
export const ENV_FILE = join(ENV_DIR, '.env');
export const EXAMPLE_FILE = join(ENV_DIR, '.env.example');
export const RESULT_FILE = join(ENV_DIR, '.install-result');
// Dropped by update.sh after pulling a new release to force a rebuild.
export const REBUILD_MARKER = join(ENV_DIR, '.needs-rebuild');

// Images produced by build.sh; all must exist for a start to succeed.
// 'hermes' is intentionally disabled (commented out in build/start/compose).
export function builtImages(): string[] {
  return ['opencode', 'bun-runner', 'liquid', 'openclaw'].map((n) => `liquidupstart/${n}:latest`);
}

export function readEnvFile() {
  const exampleText = readFileSync(EXAMPLE_FILE, 'utf8');
  const envText = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, 'utf8') : '';
  return { exampleText, envText };
}

export function envValues(): Map<string, { value: string }> {
  return existsSync(ENV_FILE) ? parseEnvValues(readFileSync(ENV_FILE, 'utf8')) : new Map();
}

// "Configured" = the form has been saved at least once. Saving fills every
// empty autogenerated secret, so an empty DATABASE_PASSWORD means .env is still
// the untouched copy of .env.example.
export function isConfigured(): boolean {
  return Boolean(envValues().get('DATABASE_PASSWORD')?.value);
}

export function dockerExitCode(args: string[], timeoutMs = 30_000): Promise<number> {
  return new Promise((res) => {
    const c = spawn('docker', args, { cwd: ENV_DIR, stdio: 'ignore' });
    const t = setTimeout(() => c.kill(), timeoutMs);
    c.on('error', () => {
      clearTimeout(t);
      res(1);
    });
    c.on('close', (code) => {
      clearTimeout(t);
      res(code ?? 1);
    });
  });
}

function dockerOutput(args: string[], timeoutMs = 30_000): Promise<string> {
  return new Promise((res) => {
    const c = spawn('docker', args, { cwd: ENV_DIR });
    let out = '';
    const t = setTimeout(() => c.kill(), timeoutMs);
    c.stdout.on('data', (d) => (out += d.toString()));
    c.on('error', () => {
      clearTimeout(t);
      res('');
    });
    c.on('close', () => {
      clearTimeout(t);
      res(out);
    });
  });
}

// The nginx proxy depends on every service, so "proxy is running" is the best
// single signal for "the stack is up".
export async function stackState(): Promise<{ running: boolean; needBuild: boolean }> {
  const [proxy, images] = await Promise.all([
    dockerOutput(['ps', '-q', '--filter', 'name=^proxy$', '--filter', 'status=running']),
    dockerExitCode(['image', 'inspect', ...builtImages()])
  ]);
  const imagesMissing = images !== 0;
  // update.sh drops the rebuild marker (and the built images). Once the images
  // are back the rebuild has happened, so clear it.
  let flagged = existsSync(REBUILD_MARKER);
  if (flagged && !imagesMissing) {
    try {
      rmSync(REBUILD_MARKER, { force: true });
    } catch {
      // best-effort; the marker is advisory
    }
    flagged = false;
  }
  return { running: proxy.trim() !== '', needBuild: imagesMissing || flagged };
}
