/**
 * A10-7 to A10-10 — a start that declares no repository needs no network, and a seeding failure costs no stack.
 *
 * Purpose: finding 4 of Timur's code review of #9. `config/scripts/start/git.sh`
 * seeds `known_hosts` from github.com **before** it reads the declaration, and
 * `exit 1`s when `ssh-keyscan` or `api.github.com` cannot be reached. Under
 * `set -e` that ends `scripts/linux/start.sh` — which ran `down.sh` 120 lines
 * earlier. So a fresh installation that is offline, behind a firewall, or merely
 * rate-limited loses the whole stack over a section of `.env` it never filled
 * in: `.env.example` promises that nothing in the git section is needed to get
 * started.
 *
 * The declaration is the thing that decides whether GitHub is needed at all, and
 * it is read 70 lines later than the call that needs it.
 *
 * Given  a project where `ssh-keyscan` and `curl` fail
 * When   `git.sh` runs with nothing declared, and again with a repository declared
 * Then   nothing is seeded and the start continues in both cases; with a
 *         declaration each entry carries the seeding failure as its error and no
 *         clone is attempted, because `StrictHostKeyChecking=yes` could only fail
 * And    a host key GitHub does not publish is still refused — that refusal
 *        stays, it simply no longer costs the stack its start
 *
 * A10-9 is the positive counterpart in two directions: with working stubs and a
 * declaration, `known_hosts` is written as before; with working stubs and
 * nothing declared, it is not written at all, which is the ordering asserted as
 * behaviour rather than as a line number.
 *
 * Test data: a stub `ssh-keyscan` that exits 1 and a stub `curl` that prints
 * nothing, against `GIT_REPOSITORIES=` (empty) and
 * `git@github.com:nocodenation/agent-skills.git|read|protected`. The working
 * stubs offer a real ed25519 key generated by the fixture, with `curl` returning
 * `{"SHA256_ED25519":"<that key's fingerprint>"}` so the published-fingerprint
 * check passes on a key this test controls. The value carries **no** `SHA256:`
 * prefix, because that is how GitHub publishes it and the script adds the prefix
 * itself; the first version of this fixture prefixed it, every comparison then
 * failed, and the fixture's defect read exactly like one in the script. A10-10
 * keeps that key and publishes
 * `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` instead, which no key can have,
 * so the offered key reads as one GitHub does not publish.
 *
 * Requirements covered: A10-7 to A10-10, finding 4 of the #9 code review.
 */
import { test, expect, describe, afterAll } from 'bun:test';
import { rmSync, existsSync, mkdirSync, writeFileSync, chmodSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tempProject, runStart, manifest } from '../lib/gitfixture';
import { sh } from '../lib/shell';

const work = tempProject('lu-a10-offline-');
afterAll(() => rmSync(work, { recursive: true, force: true }));

const DECL = 'git@github.com:nocodenation/agent-skills.git|read|protected';

// A real key, so `ssh-keygen -l` produces a real fingerprint and the working
// stubs exercise the same comparison the script makes against GitHub's list.
const keyDir = join(work, 'hostkey');
mkdirSync(keyDir, { recursive: true });
sh(['ssh-keygen', '-t', 'ed25519', '-N', '', '-C', 'probe-host', '-f', join(keyDir, 'hk')]);
const hostPub = readFileSync(join(keyDir, 'hk.pub'), 'utf8').trim().split(' ').slice(0, 2).join(' ');
// Without the SHA256: prefix, which is how api.github.com/meta publishes them --
// `"SHA256_ED25519": "+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU="` -- and the
// script prefixes them itself before comparing. Publishing the prefixed form
// here made every fingerprint read as unpublished, which looked like a defect in
// the script and was a defect in this fixture.
const fingerprint = sh(['ssh-keygen', '-l', '-f', join(keyDir, 'hk.pub')])
  .stdout.trim()
  .split(' ')[1]
  .replace(/^SHA256:/, '');

/** A bin directory whose ssh-keyscan and curl answer as the case chooses. */
function stubs(name: string, opts: { keyscan: 'fail' | 'ok'; published: string | null }): string {
  const dir = join(work, name, 'bin');
  mkdirSync(dir, { recursive: true });
  const keyscan =
    opts.keyscan === 'ok'
      ? `#!/bin/sh\necho "github.com ${hostPub}"\n`
      : `#!/bin/sh\necho "probe: no network" >&2\nexit 1\n`;
  writeFileSync(join(dir, 'ssh-keyscan'), keyscan);
  chmodSync(join(dir, 'ssh-keyscan'), 0o755);
  const curl =
    opts.published === null
      ? `#!/bin/sh\nexit 0\n`
      : `#!/bin/sh\ncat <<'JSON'\n{"SHA256_ED25519": "${opts.published}"}\nJSON\n`;
  writeFileSync(join(dir, 'curl'), curl);
  chmodSync(join(dir, 'curl'), 0o755);
  return dir;
}

function project(name: string): string {
  const p = join(work, name, 'project');
  mkdirSync(p, { recursive: true });
  return p;
}

const knownHosts = (p: string) => join(p, 'volumes', '_git-secrets', 'known_hosts');

describe('A10-7 nothing declared needs nothing from GitHub', () => {
  const p = project('empty-offline');
  const run = runStart(p, '', { pathPrefix: stubs('empty-offline', { keyscan: 'fail', published: null }) });

  test('the start continues, and nothing was seeded', () => {
    // Before: exit 1 here, and start.sh had torn the stack down 120 lines
    // earlier -- so an offline first start left the machine with no stack at all.
    expect(run.code).toBe(0);
    expect(existsSync(knownHosts(p))).toBe(false);
  });

  test('and it says nothing about GitHub, because nothing asked for it', () => {
    expect(run.output).not.toContain('could not reach github.com');
  });
});

describe('A10-8 a declaration plus a seeding failure is an error per repository, not an abort', () => {
  const p = project('declared-offline');
  const run = runStart(p, DECL, {
    pathPrefix: stubs('declared-offline', { keyscan: 'fail', published: null })
  });

  test('the start continues', () => {
    expect(run.code).toBe(0);
  });

  test('and the repository carries the reason, unattempted', () => {
    const e = manifest(p).repositories[0] as { cloned: boolean; error: string };
    expect(e.cloned).toBe(false);
    expect(e.error).toContain('github.com');
    // Not attempted: with no known_hosts, StrictHostKeyChecking=yes could only
    // fail, and "Host key verification failed" would send the operator after a
    // deploy key that is not the problem.
    expect(run.output).not.toContain('could not clone');
    expect(run.output).not.toContain('::aiw-git-key-required::');
  });
});

describe('A10-9 with GitHub reachable, the seeding happens — and only when something is declared', () => {
  test('a declared repository gets known_hosts written', () => {
    const p = project('declared-online');
    const run = runStart(p, DECL, {
      pathPrefix: stubs('declared-online', { keyscan: 'ok', published: fingerprint })
    });
    expect(run.code).toBe(0);
    expect(existsSync(knownHosts(p))).toBe(true);
    expect(readFileSync(knownHosts(p), 'utf8')).toContain('github.com');
  });

  test('and an empty declaration does not, although GitHub is reachable', () => {
    // The ordering, asserted as behaviour: the seeding now runs after the
    // declaration is read, so "nothing declared" means "nothing fetched". A line
    // number would have said the same thing less durably.
    const p = project('empty-online');
    const run = runStart(p, '', {
      pathPrefix: stubs('empty-online', { keyscan: 'ok', published: fingerprint })
    });
    expect(run.code).toBe(0);
    expect(existsSync(knownHosts(p))).toBe(false);
  });
});

describe('A10-10 a host key GitHub does not publish is still refused', () => {
  const p = project('forged');
  const run = runStart(p, DECL, {
    pathPrefix: stubs('forged', {
      keyscan: 'ok',
      published: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    })
  });

  test('nothing is written, and nothing is cloned', () => {
    // The refusal is the point of the check and it stays. What changes is its
    // cost: it is now this repository's error rather than the stack's start.
    expect(existsSync(knownHosts(p))).toBe(false);
    const e = manifest(p).repositories[0] as { cloned: boolean; error: string };
    expect(e.cloned).toBe(false);
    expect(e.error).toContain('does not publish');
  });

  test('and the start still continues', () => {
    expect(run.code).toBe(0);
  });
});
