import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { listFields, parseEnvValues, parseExample, renderEnv, formatValue } from './env-file';
import {
  isBuildAffecting,
  inputType,
  isCollapsedSection,
  isCollapsedSubheading,
  sectionDescription,
  sectionModeFromTitle,
  subheadingDescription
} from './env-meta';

const FIXTURE = `# =============================================================================
# Test Project — environment configuration
# =============================================================================
# Copy this file to .env and fill in the values.


# =============================================================================
# 1. NETWORKING
# =============================================================================
# Host ports published by the proxy.
SYSTEM_HTTP_PORT=8888


# =============================================================================
# 2. SECRETS - AUTOGENERATED ONCE IF VALUES ARE EMPTY
# =============================================================================

# --- PostgreSQL (main app database) ---
DATABASE_PASSWORD=
# Multi-line help:
# spans two comment lines.
JWT_SECRET=


# =============================================================================
# 3. ACCOUNTS - USER CAN CHANGE ON FIRST RUN
# =============================================================================
ADMIN_EMAIL=user@example.org


# =============================================================================
# 4. INTERNAL - SCRIPTS GENERATE IT - DO NOT SHOW UI
# =============================================================================
API_KEY=placeholder


# =============================================================================
# 5. BUILD CONFIG
# =============================================================================

# SYSTEM_DEPENDENCIES
# -------------------
# Paragraph one about deps.
#
# Example: SYSTEM_DEPENDENCIES="ffmpeg, jq"
SYSTEM_DEPENDENCIES=""

# -----------------------------------------------------------------------------
# PER-IMAGE OVERRIDES
# -----------------------------------------------------------------------------
NIFI_SYSTEM_DEPENDENCIES_MODE="add" # add | override
NIFI_USERNAME="nifi"
`;

describe('parseExample', () => {
  const sections = parseExample(FIXTURE);

  test('splits sections by banners and parses behavior markers', () => {
    expect(sections.map((s) => s.displayTitle)).toEqual([
      'Test Project — environment configuration',
      '1. NETWORKING',
      '2. SECRETS',
      '3. ACCOUNTS',
      '4. INTERNAL',
      '5. BUILD CONFIG'
    ]);
    expect(sections.map((s) => s.mode)).toEqual([
      'normal',
      'normal',
      'autogenerate',
      'normal',
      'hidden',
      'normal'
    ]);
  });

  test('attaches contiguous comments above a key as help', () => {
    const fields = listFields(sections);
    const jwt = fields.find((f) => f.field.key === 'JWT_SECRET');
    expect(jwt?.field.help).toEqual(['Multi-line help:', 'spans two comment lines.']);
    // follows a subheading, not a help comment
    const db = fields.find((f) => f.field.key === 'DATABASE_PASSWORD');
    expect(db?.field.help).toEqual([]);
  });

  test('recognizes both subheading styles', () => {
    const build = sections.find((s) => s.displayTitle === '5. BUILD CONFIG');
    const subs = build!.items.filter((i) => i.kind === 'subheading');
    expect(subs.map((s) => (s.kind === 'subheading' ? s.text : ''))).toEqual([
      'SYSTEM_DEPENDENCIES',
      'PER-IMAGE OVERRIDES'
    ]);
    const secrets = sections.find((s) => s.displayTitle === '2. SECRETS');
    const oneLiner = secrets!.items.find((i) => i.kind === 'subheading');
    expect(oneLiner && oneLiner.kind === 'subheading' ? oneLiner.text : '').toBe(
      'PostgreSQL (main app database)'
    );
  });

  test('remembers defaults and quoting', () => {
    const fields = listFields(sections);
    const get = (key: string) => fields.find((f) => f.field.key === key)!.field;
    expect(get('SYSTEM_HTTP_PORT')).toMatchObject({ defaultValue: '8888', quoted: false });
    expect(get('SYSTEM_DEPENDENCIES')).toMatchObject({ defaultValue: '', quoted: true });
    expect(get('NIFI_SYSTEM_DEPENDENCIES_MODE')).toMatchObject({ defaultValue: 'add', quoted: true });
  });
});

describe('parseEnvValues', () => {
  test('parses quoted, unquoted and inline-commented values; last occurrence wins', () => {
    const values = parseEnvValues(
      'A=1\nB="two words" # comment\nC=bare # trailing\nA=2\n# X=ignored\n'
    );
    expect(values.get('A')?.value).toBe('2');
    expect(values.get('B')).toMatchObject({ value: 'two words', quoted: true });
    expect(values.get('C')?.value).toBe('bare');
    expect(values.has('X')).toBe(false);
  });
});

describe('renderEnv', () => {
  test('round-trips the fixture unchanged when values equal the defaults', () => {
    const values = new Map(
      listFields(parseExample(FIXTURE)).map(({ field }) => [
        field.key,
        { value: field.defaultValue, quoted: field.quoted }
      ])
    );
    expect(renderEnv(FIXTURE, values, [])).toBe(FIXTURE);
  });

  test('substitutes values and appends custom keys', () => {
    const values = new Map([['SYSTEM_HTTP_PORT', { value: '9000', quoted: false }]]);
    const out = renderEnv(FIXTURE, values, ['MY_CUSTOM=kept verbatim # with comment']);
    expect(out).toContain('SYSTEM_HTTP_PORT=9000');
    expect(out).toContain('# CUSTOM KEYS');
    expect(out).toContain('MY_CUSTOM=kept verbatim # with comment');
    expect(out).toContain('NIFI_USERNAME="nifi"');
  });

  test('keeps inline comments on substituted lines', () => {
    const values = new Map([['NIFI_SYSTEM_DEPENDENCIES_MODE', { value: 'override', quoted: true }]]);
    expect(renderEnv(FIXTURE, values, [])).toContain(
      'NIFI_SYSTEM_DEPENDENCIES_MODE="override" # add | override'
    );
  });
});

describe('formatValue', () => {
  test('quotes when needed', () => {
    expect(formatValue('plain', false)).toBe('plain');
    expect(formatValue('two words', false)).toBe('"two words"');
    expect(formatValue('has#hash', false)).toBe('"has#hash"');
    expect(formatValue('say "hi"', false)).toBe('"say \\"hi\\""');
    expect(formatValue('', true)).toBe('""');
    expect(formatValue('', false)).toBe('');
  });
});

describe('env-meta', () => {
  test('classifies build-affecting keys', () => {
    expect(isBuildAffecting('SYSTEM_DEPENDENCIES')).toBe(true);
    expect(isBuildAffecting('HERMES_POST_INSTALLATION_COMMANDS_MODE')).toBe(true);
    expect(isBuildAffecting('OPENCLAW_ENABLE_CLAUDE_CLI')).toBe(true);
    expect(isBuildAffecting('DATABASE_PASSWORD')).toBe(false);
  });

  test('picks input widgets', () => {
    expect(inputType('OPENCLAW_ENABLE_CLAUDE_CLI')).toBe('checkbox');
    expect(inputType('NIFI_SYSTEM_DEPENDENCIES_MODE')).toBe('select-mode');
    expect(inputType('SYSTEM_HTTP_PORT')).toBe('number');
    expect(inputType('OPENCODE_TIMEOUT')).toBe('number');
    expect(inputType('NIFI_PASSWORD')).toBe('password');
    expect(inputType('POSTGREST_JWT_SECTET')).toBe('password');
    expect(inputType('OPENCODE_MODEL')).toBe('text');
  });

  test('collapse defaults: OPENCODE section and PER-IMAGE OVERRIDES subheading', () => {
    expect(isCollapsedSection('7. OPENCODE CONFIGURATION')).toBe(true);
    expect(isCollapsedSection('6. OPENCLAW CONFIGURATION')).toBe(false);
    expect(isCollapsedSubheading('PER-IMAGE OVERRIDES')).toBe(true);
    expect(isCollapsedSubheading('SYSTEM_DEPENDENCIES')).toBe(false);
  });

  test('section descriptions: keyword match with first-sentence fallback', () => {
    expect(sectionDescription('1. NETWORKING', 'whatever')).toContain('Host ports');
    expect(
      sectionDescription('2. SERVICE SECRETS & CREDENTIALS - AUTOGENERATED ONCE IF VALUES ARE EMPTY', '')
    ).toContain('generated automatically');
    expect(sectionDescription('UNKNOWN SECTION', 'First sentence. Second sentence.')).toBe(
      'First sentence.'
    );
    expect(sectionDescription('UNKNOWN SECTION', '')).toBe('');
    expect(subheadingDescription('PER-IMAGE OVERRIDES', '')).toContain('single image');
    expect(subheadingDescription('OTHER', 'Fallback text here. More.')).toBe('Fallback text here.');
  });

  test('strips marker suffixes from display titles', () => {
    expect(sectionModeFromTitle('2. SECRETS - AUTOGENERATED ONCE IF VALUES ARE EMPTY')).toEqual({
      mode: 'autogenerate',
      displayTitle: '2. SECRETS'
    });
    expect(sectionModeFromTitle('1. NETWORKING')).toEqual({
      mode: 'normal',
      displayTitle: '1. NETWORKING'
    });
  });
});

// On the host (not the docker build context) the real .env.example exists;
// validate it too so parser regressions surface against the live file.
const realExample = join(import.meta.dir, '../../../.env.example');
if (existsSync(realExample)) {
  describe('real .env.example', () => {
    const text = readFileSync(realExample, 'utf8');

  test('round-trips byte-identically', () => {
    const values = new Map(
      listFields(parseExample(text)).map(({ field }) => [
        field.key,
        { value: field.defaultValue, quoted: field.quoted }
      ])
    );
    expect(renderEnv(text, values, [])).toBe(text);
  });

  test('finds the marked sections with their fields', () => {
    const sections = parseExample(text);
    const autogen = sections.find((s) => s.mode === 'autogenerate');
    const hidden = sections.find((s) => s.mode === 'hidden');
    const keysIn = (s: ReturnType<typeof parseExample>[number]) =>
      s.items.flatMap((i) => (i.kind === 'field' ? [i.field.key] : []));
    expect(keysIn(autogen!)).toContain('DATABASE_PASSWORD');
    expect(keysIn(hidden!)).toContain('API_KEY');
  });

  test('finds every KEY= line of the file as a field', () => {
    const parsedKeys = listFields(parseExample(text)).map(({ field }) => field.key);
    const rawKeys = text
      .split('\n')
      .map((l) => l.match(/^([A-Za-z_][A-Za-z0-9_]*)=/)?.[1])
      .filter((k): k is string => k !== undefined);
    expect(parsedKeys).toEqual(rawKeys);
    expect(parsedKeys.length).toBeGreaterThan(40);
  });
  });
}
