// Classification of .env keys and section behavior. Section behavior comes from
// marker suffixes in .env.example titles (e.g. "... - AUTOGENERATED ONCE IF
// VALUES ARE EMPTY"); key-pattern matching only picks the input widget and the
// rebuild-needed flag.

export type SectionMode = 'normal' | 'autogenerate' | 'hidden';

// Host ports published by the nginx proxy. Empty in .env.example, seeded on
// first setup (next free port if taken), then locked — services are configured
// against the initial ports, so changing them later would break the install.
export const SYSTEM_PORT_DEFAULTS: Record<string, string> = {
  SYSTEM_HTTP_PORT: '8888',
  SYSTEM_HTTPS_PORT: '8833'
};

export function isSystemPort(key: string): boolean {
  return key in SYSTEM_PORT_DEFAULTS;
}

export function sectionModeFromTitle(title: string): { mode: SectionMode; displayTitle: string } {
  let mode: SectionMode = 'normal';
  let marked = false;
  if (/AUTOGENERATED ONCE IF VALUES ARE EMPTY/i.test(title)) {
    mode = 'autogenerate';
    marked = true;
  } else if (/DO NOT SHOW UI/i.test(title)) {
    mode = 'hidden';
    marked = true;
  } else if (/USER CAN CHANGE ON FIRST RUN/i.test(title)) {
    marked = true;
  }
  const displayTitle = marked ? title.split(' - ')[0].trim() : title;
  return { mode, displayTitle };
}

// Changing any of these requires rebuilding images (IMAGE BUILD CONFIGURATION
// knobs consumed by build.sh, plus the OpenClaw build switch).
export function isBuildAffecting(key: string): boolean {
  return (
    key === 'OPENCLAW_ENABLE_CLAUDE_CLI' ||
    /SYSTEM_DEPENDENCIES(_MODE)?$/.test(key) ||
    /POST_INSTALLATION_COMMANDS(_MODE)?$/.test(key)
  );
}

export function looksSecret(key: string): boolean {
  return /PASSWORD|SECRET|SECTET|_TOKEN$|_API_KEY$/.test(key);
}

export type InputType = 'text' | 'password' | 'number' | 'checkbox' | 'select-mode';

export function inputType(key: string): InputType {
  // OPENCLAW_ENABLE_* toggles are 0/1 flags — render as checkboxes.
  if (/^OPENCLAW_ENABLE_/.test(key)) return 'checkbox';
  if (/_MODE$/.test(key)) return 'select-mode';
  if (/PORT$|TIMEOUT$/.test(key)) return 'number';
  if (looksSecret(key)) return 'password';
  return 'text';
}

// Sections rendered collapsed by default (matched against the full banner
// title); the autogenerate-marked section is collapsed independently.
export function isCollapsedSection(title: string): boolean {
  return /OPENCODE CONFIGURATION/i.test(title);
}

// Subheadings that fold the rest of their section into a nested collapsible.
export function isCollapsedSubheading(text: string): boolean {
  return /PER-IMAGE OVERRIDES/i.test(text);
}

// One-liners shown in a section header so a collapsed card still describes its
// contents. Keyword-matched against the full banner title (so renumbering
// sections doesn't break it); no entry falls back to the leading paragraph's
// first sentence.
const SECTION_DESCRIPTIONS: [RegExp, string][] = [
  [/NETWORKING/i, "Host ports for the stack's web interfaces (<name>.localhost)."],
  [/AUTOGENERATED ONCE/i, 'Internal service passwords & tokens — generated automatically on save.'],
  [/USER CAN CHANGE ON FIRST RUN/i, 'Credentials you may want to set yourself before the first start.'],
  [/LLM PROVIDER API KEYS/i, 'API keys of LLM providers, used by the AI services (optional).'],
  [/OPENCLAW CONFIGURATION/i, 'Model & backend selection for OpenClaw, the recommended AI harness.'],
  [/OPENCODE CONFIGURATION/i, 'Model, Ollama endpoint and timeout settings for the OpenCode web UI.'],
  [/LIQUID AUTHENTICATION/i, 'Login and TLS keystore credentials for Liquid.'],
  [/IMAGE BUILD CONFIGURATION/i, 'Extra packages & commands baked into the Docker images by build.sh.']
];

const SUBHEADING_DESCRIPTIONS: [RegExp, string][] = [
  [/PER-IMAGE OVERRIDES/i, 'Extend or replace the global build settings for a single image.']
];

function firstSentence(text: string): string {
  const m = text.match(/^(.*?[.!?])(\s|$)/);
  return m ? m[1] : text.slice(0, 120);
}

export function sectionDescription(title: string, firstParagraph: string): string {
  for (const [re, desc] of SECTION_DESCRIPTIONS) if (re.test(title)) return desc;
  return firstParagraph ? firstSentence(firstParagraph) : '';
}

export function subheadingDescription(text: string, firstParagraph: string): string {
  for (const [re, desc] of SUBHEADING_DESCRIPTIONS) if (re.test(text)) return desc;
  return firstParagraph ? firstSentence(firstParagraph) : '';
}
