/**
 * M-A1 · Component · The new .env.example section parses as the dashboard reads it
 *
 * Purpose:  .env.example is not just documentation, it is the schema the
 *           dashboard renders its configuration form from. A section that reads
 *           well to a human but does not parse is a silent failure: the keys
 *           simply never appear in the UI. This runs the real parser over the
 *           real file rather than a fixture, which is why the coupling to the
 *           dashboard library was accepted when the case was signed off.
 * Given:    .env.example with the "10. GIT INTEGRATION" section.
 * When:     parseExample and sectionModeFromTitle are applied to it.
 * Then:     The section is recognised, both GIT_* keys are listed as fields with
 *           help text, and the section mode is normal so it is shown in the UI.
 * Covers:   A1-1, A1-2, FR10
 * Unhappy:  A section title carrying a mode marker would parse as hidden or
 *           autogenerate; the mode assertion is what catches that.
 */
import { test, expect } from 'bun:test';
import { parseExample, listFields } from '../../dashboard/src/lib/env-file';
import { sectionModeFromTitle } from '../../dashboard/src/lib/env-meta';
import { envExampleText } from '../lib/compose-file';

const sections = parseExample(envExampleText());
const git = sections.find((s) => /GIT INTEGRATION/i.test(s.title));

test('A1-1 the git section is recognised by the parser', () => {
  expect(git).toBeDefined();
  expect(git!.title).toMatch(/^10\./);
});

test('A1-1 both keys are listed as fields carrying help text', () => {
  const fields = listFields(sections)
    .filter((f) => /GIT INTEGRATION/i.test(f.section.title))
    .map((f) => f.field);
  const keys = fields.map((f) => f.key);
  expect(keys).toContain('GIT_USER_NAME');
  expect(keys).toContain('GIT_USER_EMAIL');
  for (const f of fields) {
    expect(f.help.join(' ').trim().length).toBeGreaterThan(0);
  }
});

test('A1-2 the section is shown in the dashboard, not hidden or autogenerated', () => {
  expect(sectionModeFromTitle(git!.title).mode).toBe('normal');
  expect(git!.mode).toBe('normal');
});
